version: 2.1
orbs:
  node: circleci/node@3.0.1
  aws-s3: circleci/aws-s3@2.0.0
jobs:
  build:
    docker:
      - image: circleci/node:14-browsers-legacy
    steps:
      - checkout
      - run: npm install
      - run: npm run build
  release-version:
    docker:
      - image: circleci/node:14-browsers-legacy
    steps:
      - checkout
      - run: npm install
      - run: npx semantic-release
workflows:
  version: 2
  build-deploy-release:
    jobs:
      - node/test
      - build:
          requires:
            - node/test
      - release-version:
          requires:
            - build
          filters:
            branches:
              only: main
